"""
echo Project (Generated by Panther on 2023-09-16)
"""

from pathlib import Path


BASE_DIR = Path(__name__).resolve().parent

SECRET_KEY = 'fHrIYx3yK0J_UG0K0zD6miLPNy1esoYXzVsvif6e7rY='

MIDDLEWARES = [
    ('panther.middlewares.db.DatabaseMiddleware', {'url': f'pantherdb://{BASE_DIR}/database.pdb'}),
]

MONITORING = True

LOG_QUERIES = True

URLs = 'core.urls.url_routing'
